languages_def <- list()
languages_def[["en1"]] <- c("ENGLISH", "ARABIC", "BULGARIAN", "CHINESE", "DUTCH", "FRENCH", "GERMAN", "HAITIAN", "HINDI", "ITALIAN", "KOREAN", "LITHUANIAN", "POLISH", "PORTUGUESE", "PUNJABI", "ROMANIAN", "RUSSIAN", "SPANISH", "TAGALOG", "VIETNAMESE", "OTHER_LANGUAGE")
languages_def[["de1"]] <- c("GERMAN", "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "ITALIAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN", "SPANISH", "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")
languages_def[["it1"]] <- c("ITALIAN", "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "GERMAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN", "SPANISH", "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")
languages_def[["es1"]] <- c("SPANISH", "VALENCIAN", "CATALAN",  "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "GERMAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN",  "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")

languages_def[["en2"]] <- c("NONE", "ENGLISH", "ARABIC", "BULGARIAN", "CHINESE", "DUTCH", "FRENCH", "GERMAN", "HAITIAN", "HINDI", "ITALIAN", "KOREAN", "LITHUANIAN", "POLISH", "PORTUGUESE", "PUNJABI", "ROMANIAN", "RUSSIAN", "SPANISH", "TAGALOG", "VIETNAMESE", "OTHER_LANGUAGE")
languages_def[["de2"]] <- c("NONE", "GERMAN", "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "ITALIAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN", "SPANISH", "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")
languages_def[["it2"]] <- c("NONE", "ITALIAN", "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "GERMAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN", "SPANISH", "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")
languages_def[["es2"]] <- c( "NONE", "SPANISH", "VALENCIAN", "CATALAN",  "ALBANIAN", "ARABIC", "BULGARIAN", "CHINESE", "ENGLISH", "FRENCH", "GREEK", "GERMAN", "JAPANESE", "KURDISH", "PASHTO", "PERSIAN", "POLISH", "ROMANIAN", "RUSSIAN", "SERBIAN",  "TURKISH", "HUNGARIAN", "OTHER_LANGUAGE")

language_codes_def <- c(
  "ALBANIAN" = "sq",
  "ARABIC" = "ar",
  "BULGARIAN" = "bg" ,
  "CATALAN" = "cat",
  "CHINESE" = "zh",
  "DUTCH" = "nl",
  "ENGLISH" = "en",
  "FRENCH" = "fr",
  "GERMAN" = "de",
  "GREEK" = "gr",
  "HAITIAN" = "ht",
  "HINDI" =  "hi",
  "HUNGARIAN" = "hu",
  "ITALIAN" = "it",
  "JAPANESE" = "jp",
  "KOREAN" = "ko" ,
  "KURDISH" = "ku",
  "LITHUANIAN" =  "lt",
  "OTHER_LANGUAGE" = "other",
  "NONE" = "none",
  "PASHTO" = "ps",
  "PERSIAN" = "fa",
  "POLISH" = "pl",
  "PORTUGUESE" =  "pt",
  "PUNJABI" = "pa",
  "ROMANIAN" = "ro",
  "RUSSIAN" = "ru",
  "SERBIAN" = "sr",
  "SPANISH" = "es",
  "TAGALOG" = "tl",
  "TURKISH" = "tr" ,
  "VALENCIAN" = "vlca",
  "VIETNAMESE" = "vi")

